# 多模态embedding模型配置

# 模型实例化配置
_target_: src.models.embedding.MultiModalEmbeddingModel

# 模型超参数
embed_dim: 512
temperature: 0.07
learning_rate: 1e-4
weight_decay: 1e-4
warmup_epochs: 10
modality_weights: [1.0, 1.0, 1.0]  # [aerial-s1, aerial-s2, s1-s2]

# 网络架构配置
backbone: "vit_b_16"  # resnet50 或 vit_b_16

# 日志配置
log_wandb: True 