# @package _global_

defaults:
  - _self_
  - dataset: treesat
  - model: multimodal_embedding
  - callbacks: default
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

# 数据模块配置
datamodule:
  _target_: src.data.hydra_datamodule.HydraDataModule
  train_dataset_config: ${dataset.train_dataset}
  val_dataset_config: ${dataset.val_dataset}
  test_dataset_config: ${dataset.test_dataset}
  global_batch_size: ${dataset.global_batch_size}
  num_workers: 4
  num_nodes: ${trainer.num_nodes}
  num_devices: ${trainer.devices}
  data_path: ${data_dir}
  train_partition: ${partition}

# 标签和元数据
tags: ["multimodal", "embedding", "treesat"]

# 路径配置
data_dir: ${paths.data_dir}

# 训练控制
train: True  # 设置False跳过模型训练
test: True   # 在测试集上评估，使用训练期间获得的最佳模型权重
compile: False  # 使用pytorch 2.0编译模型以加快训练速度

# checkpoint恢复
ckpt_path: null  # 简单提供checkpoint路径以恢复训练

# 随机种子
seed: 42

# 数据分区
partition: 0.01

# 最大训练轮数
max_epochs: 100

# 离线模式
offline: False

# 实验名称
experiment_name: treesat_multimodal_embedding

# 优化指标（用于超参数搜索）
optimized_metric: "val/total_loss" 